name: Build Desktop App

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Create virtual environment and install dependencies
    - name: Set up virtual environment and install dependencies
      shell: pwsh
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller

    # 4️⃣ Build executable using PyInstaller
    - name: Build executable
      shell: pwsh
      run: |
        .\venv\Scripts\Activate.ps1
        python -m pyinstaller --noconsole --onefile desktop_app.py

    # 5️⃣ Create GitHub Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: desktop-app-v${{ github.run_number }}
        release_name: Desktop App Build #${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 6️⃣ Upload exe to Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/desktop_app.exe
        asset_name: desktop_app.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
