name: Build Desktop App

on:
  workflow_dispatch:  # manually trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller


    - name: Build executable
      run: |
        python -m pyinstaller --noconsole --onefile desktop_app.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      with:
        tag_name: desktop-app-v${{ github.run_number }}
        release_name: Desktop App Build #${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/desktop_app.exe
        asset_name: desktop_app.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
