name: LTV CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ref_month:
        description: 'Reference month for preprocessing'
        required: true
        default: 'm5'
      debug:
        description: 'Enable debug mode (true/false)'
        required: false
        default: 'true'
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  # -------------------------------
  # Job 1: Lint & Format
  # -------------------------------
  lint:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: black src/

      - name: Auto commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format with Black"

      - name: Run Pylint
        run: pylint src/ --disable=C0116,R0913,R0914 || true

  # -------------------------------
  # Job 2: Run & Debug main.py
  # -------------------------------
  run-debug:
    runs-on: ubuntu-latest
    needs: lint   # 等待 lint 完成再运行
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py with debug
        run: |
          set -x
          mkdir -p logs
          echo "::group::Running src/main.py"
          python src/main.py > logs/main_run.log 2>&1
          echo "::endgroup::"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: main-debug-logs
          path: logs/

      - name: Upload model outputs
        uses: actions/upload-artifact@v4
        with:
          name: model-outputs
          path: outputs/
