name: Code Format & Lint Check

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
      
permissions:
  contents: write 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (auto format)
        run: |
          black .

      - name: Auto commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format with Black"

      - name: Run Pylint (code quality)
        run: |
          pylint $(git ls-files '*.py') || true
